Repository palantir/conjure-typescript, pull requests merged in 2025-01, with the labels that each got.

#302 Add type assignment for empty union generations
  changelog/@unreleased/pr-302.v2.yml
  src/commands/generate/__tests__/resources/definitions/example-types.yml
  src/commands/generate/__tests__/resources/flavored-test-cases/example-types/product/emptyUnionTypeExample.ts
  src/commands/generate/__tests__/resources/readonly-test-cases/example-types/product/emptyUnionTypeExample.ts
  src/commands/generate/__tests__/resources/test-cases/example-types/product/emptyUnionTypeExample.ts
  src/commands/generate/typeGenerator.ts
Labels: autorelease

#303 Code improvements
  src/commands/generate/generateCommand.ts
  src/commands/generate/imports.ts
  src/commands/generate/serviceGenerator.ts
  src/commands/generate/typeGenerator.ts
  src/commands/generate/utils.ts
Labels: merge when ready, no changelog

#308 Eliminate `TsReturnTypeVisitor` and `TsArgumentTypeVisitor`
  changelog/@unreleased/pr-308.v2.yml
  src/__tests__/resolveTsTypeTests.ts
  src/__tests__/utils/constants.ts
  src/commands/generate/__tests__/errorGeneratorTest.ts
  src/commands/generate/__tests__/generatorTest.ts
  src/commands/generate/__tests__/importsTest.ts
  src/commands/generate/__tests__/resources/constants.ts
  src/commands/generate/__tests__/serviceGeneratorTest.ts
  src/commands/generate/__tests__/simpleAstTest.ts
  src/commands/generate/__tests__/testTypesGeneratorTest.ts
  src/commands/generate/__tests__/tsArgumentTypeVisitorTests.ts
  src/commands/generate/__tests__/tsReturnTypeVisitorTest.ts
  src/commands/generate/__tests__/typeGeneratorTest.ts
  src/commands/generate/errorGenerator.ts
  src/commands/generate/imports.ts
  src/commands/generate/serviceGenerator.ts
  src/commands/generate/tsArgumentTypeVisitor.ts
  src/commands/generate/tsReturnTypeVisitor.ts
  src/commands/generate/typeGenerator.ts
  src/utils/resolveTsType.ts
Labels: merge when ready

#309 Eliminate `ImportsVisitor`
  changelog/@unreleased/pr-309.v2.yml
  src/__tests__/resolveImportsTests.ts
  src/__tests__/utils/createSimpleObject.ts
  src/commands/generate/__tests__/importsTest.ts
  src/commands/generate/__tests__/testTypesGeneratorTest.ts
  src/commands/generate/errorGenerator.ts
  src/commands/generate/generator.ts
  src/commands/generate/imports.ts
  src/commands/generate/serviceGenerator.ts
  src/commands/generate/simpleAst.ts
  src/commands/generate/typeGenerator.ts
  src/utils/fileUtils.ts
  src/utils/resolveImports.ts
Labels: merge when ready

#310 Eliminate remaining visitors
  changelog/@unreleased/pr-310.v2.yml
  src/__tests__/resolveMediaTypeTests.ts
  src/commands/generate/__tests__/mediaTypeVisitorTest.ts
  src/commands/generate/generator.ts
  src/commands/generate/mediaTypeVisitor.ts
  src/commands/generate/serviceGenerator.ts
  src/commands/generate/stringConversionTypeVisitor.ts
  src/utils/resolveMediaType.ts
  src/utils/resolveStringConversion.ts
Labels: merge when ready

#311 Update `README.md`
  README.md
  changelog/@unreleased/pr-311.v2.yml
  jest.config.js
  src/tsconfig.karma.json
  versions.props
Labels: merge when ready
